version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces:cached
    # Dev Container가 사용할 포트 포워딩 (선택 사항)
    # ports:
    #   - "8000:8000"
    command: sleep infinity # Dev Container가 계속 실행되도록 유지
    env_file:
      - .env # .env 파일에서 환경 변수 로드
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local-database
    volumes:
      - db_data:/var/lib/postgresql/data
    ports: # 로컬 개발용이므로 외부 노출
      - "5432:5432"

volumes:
  db_data:
